import Head from "next/head";
import styles from "../styles/Home.module.css";
import Form from "../@/components/Form";
import AllBlogsCard from "../@/components/AllBlogsCard";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-between p-4 md:p-8 lg:p-12">
        <Form />
        <AllBlogsCard />
      </main>
    </div>
  );
}
