import Head from "next/head";
import styles from "../styles/Home.module.css";
import Form from "../@/components/Form";
import AllBlogsCard from "../@/components/AllBlogsCard";
import { getAllBlogs } from "../@/lib/supabase";
import { Suspense } from "react";
import Loader from "../@/components/Loader";

export const runtime = "experimental-edge";

export default function Home({ blogs }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-between p-4 md:p-8 lg:p-12">
        <Form />
        <Suspense
          fallback={
            <div>
              <Loader message="Loading blogs..." />
            </div>
          }
        >
          <AllBlogsCard blogs={blogs.data} />
        </Suspense>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const blogs = await getAllBlogs();
  return { props: { blogs } };
};
